### ISSUE TITLE
Cannot run pubsub example

### ISSUE THREAD

**Issue by crandmck** [strongloop/strong-pubsub#12]
Following the instructions in https://github.com/strongloop/strong-pubsub-example, I am unable to run the example app.

```
$ cd strong-pubsub-example
$ npm i
...
$ node .
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)
```

**Comment by crandmck** [comment]
Needed to have `/usr/loca/sbin` on my path.

**Comment by ritch** [comment]
> Needed to have /usr/loca/sbin on my path.

Specifically you need `mosquitto` in your `PATH`.
