### ISSUE TITLE
Diff. with Mosca / Mosquitto ?

### ISSUE THREAD

**Issue by KrishnaPG** [strongloop/strong-pubsub#15]
Thanks for sharing this - trying to understand this work better.

So, where does this fit in the MQTT ecospace. Is this a broker and replacement to Mosca / Mosquitto or works with them or .. ??

**Comment by ritch** [comment]
This works with mosquitto and mosca. It isn't a broker itself. Also keep in mind that `mqtt` is only one of the `Adapter`s. Given the appropriate adapter (eg. redis) you can connect to other brokers (or MQs).
