### ISSUE TITLE
How does strong-mq overlap strong-pubsub ?

### ISSUE THREAD

**Issue by afaucogney** [strongloop/strong-pubsub#19]
Sorry if the question amy appear stupid, but could you explain the diff and tell me which component I can rely on (it both module aim the same target)

Thanks

**Comment by ritch** [comment]
Strong-mq is oriented for interacting with message queues and their different queue styles. This modules is specifically for pubsub which might happen to be over a message queue.

**Comment by ritch** [comment]
Closing for now. This isn't a stupid question. We should include a note in the readme.
