### ISSUE TITLE
Example snippets in README

### ISSUE THREAD

**Issue by ritch** [strongloop/strong-pubsub#4]
**Create the following examples.**

### REAME

**Bridge**

Showing how to connect a `Client` to a `Bridge` and then a `Bridge` to a broker (using another `Client).

```js
server.on('connection', function(connection) {
  var bridge = new Bridge(
    new MqttConnection(connection),
    new Client({port: MOSQUITTO_PORT}, Adapter)
  );

  bridge.connect();
});
```

**Transport Swapping (tls)**

```js
//
// client side transport switching
//
var Adapter = require('strong-pubsub-mqtt');

// default
var TcpTransport = require('net'); // tcp (the default)
var client = new Client({host: 'localhost', port: 3000}, Adapter, TcpTransport);

// primus
var PrimusTransport = require('strong-pubsub-primus');
var client = new Client({host: 'localhost', port: 3000}, Adapter, PrimusTransport);

// tls
var TlsTransport = require('tls');
var client = new Client({host: 'localhost', port: 3000}, Adapter, TlsTransport);

//
// bridge transport swapping
//
var primusServer = PrimusTransport.createServer();
var tlsServer = TlsTransport.createServer();
var tcpServer = TcpTransport.createServer();

primusServer.on('connection', bridgeConnection);
tlsServer.on('connection', bridgeConnection);
tcpServer.on('connection', bridgeConnection);

function bridgeConnection(connection) {
  var bridge = new Bridge(
    new MqttConnection(connection),
    new Client({port: MOSQUITTO_PORT}, Adapter)
  );

  bridge.connect();
}
```

**Comment by ritch** [comment]
@crandmck I can help you create these. Ping me if you need anything.

**Comment by Telemakhos** [comment]
Guys just wanted to put this [Node-based MQTT broker](https://github.com/mcollina/mosca) in your radar just in case you want to use it for some example. It can be installed as npm package in any project so I thought it can be really convenient for some demo (for the sake of simplicity)

**Comment by ritch** [comment]
@Telemakhos thanks for the heads up. I am well aware of mosca :). I like the idea of replacing mosquitto with mosca in our examples... Good idea :+1:

**Comment by crandmck** [comment]
@ritch yes I need help.  Where can I find the examples?  I'm not sure I'm the best one to create them.

**Comment by crandmck** [comment]
Currently blocked by #12

**Comment by crandmck** [comment]
@ritch Where are we with this?  Is there still work to be done?

**Comment by crandmck** [comment]
Added to README:
- https://github.com/strongloop/strong-pubsub/blob/master/README.md#creating-a-bridge
- https://github.com/strongloop/strong-pubsub/blob/master/README.md#transport-swapping

@ritch PTAL.  I _think_ I put the example snippets in the right places.
