### ISSUE TITLE
LoopBack Integration Example (pubsub reference example)

### ISSUE THREAD

**Issue by ritch** [strongloop/strong-pubsub#7]
Integrate the following:

 - angular
 - loopback
 - mongodb
 - pubsub

The example should illustrate realtime model data binding.

@altsang if you have additional ideas please chime in here...

**Comment by ritch** [comment]
https://github.com/strongloop/loopback-example-pubsub/wiki
https://github.com/strongloop/loopback-example-pubsub

**Comment by behrad** [comment]
@ritch above links are invalid (404)

**Comment by chandadharap** [comment]
@behrad Thanks for pointing out. We'll open them up next week, still in review.

**Comment by glassbox** [comment]
@chandadharap Any ETA for this feature please. Can't wait to try it out?

**Comment by chandadharap** [comment]
@Imed in the week of the 26th. (Next week)


On Wednesday, April 22, 2015, Imed <notifications@github.com> wrote:

> @chandadharap <https://github.com/chandadharap> Any ETA for this feature
> please. Can't wait to try it out?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/strongloop/strong-pubsub/issues/7#issuecomment-95357471>
> .
>


-- 
Chanda Dharap
Director, Engineering
@StrongLoop Inc
(510) 304-3924
chanda@strongloop.com

*StrongLoop <http://strongloop.com/>** makes it easy to **develop APIs
<http://strongloop.com/mobile-application-development/loopback/>** in Node,
plus get DevOps capabilities
<http://strongloop.com/node-js-performance/strongops/> like monitoring,
debugging and clustering**.*

**Comment by chandadharap** [comment]
@ritch Can be opened up. LGTM

**Comment by chandadharap** [comment]
Close after README is updated.

**Comment by chandadharap** [comment]
@ritch This is in review? We've released I believe. I'll close.
