### ISSUE TITLE
Review Examples

### ISSUE THREAD

**Issue by ritch** [strongloop/strong-pubsub#8]
I'd like some eyes on the examples before I polish them. Also I need some help with the readmes. Esepcially making them consistent with our other examples.

**Comment by superkhau** [comment]
- [ ] review the client example (angular client, loopback server, pubsub)
- [ ] review the server
- [ ] write a section in the docs for each bottom item

---

- [ ] sync
- [ ] encoding
 - [ ] we accept strings, you can encode them however you want
  - [ ] its up to you to do encoding / decoding
 -  [ ] mention JSON (we support this, but you have to do)
 -  [ ] mention URL encoding (recommend for this app)
-  [ ] an example connector or model that wraps pubsub
 -  [ ] req: client.publish() isn't in the app code
 -  [ ] instead: use loopback-connector-pubsub
  -  [ ] req: implement a first pass at connector-pubsub
-  [ ] a reference implementation of `loopback-pubsub`

**Comment by superkhau** [comment]
@0candy Reassigning to you since you are the expert. Feel free to prioritize accordingly.

**Comment by crandmck** [comment]
@0candy Can we close this?  We have these docs: http://loopback.io/doc/en/lb3/Publish-subscribe-messaging.html  that all come from the various READMEs.

**Comment by 0candy** [comment]
The unchecked items listed above by @superkhau is not done, I don't think we can close this yet.
@ritch Do you agree?

**Comment by dhmlau** [comment]
Closing it because I'm not sure how relevant this issue is, and we don't have bandwidth at this moment for this task.
